version: "3.7"
services:
  envoy:
    image: envoyproxy/envoy:v1.19.1
    container_name: envoy
    volumes:
    - ./envoy.yaml:/etc/envoy/envoy.yaml:ro
    ports:
    - 8000:8000
    - 9901:9901
  xds:
    build: .
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
